# Thunderbird Email Organization Setup Script
# This script helps create the folder structure and import filters

echo "=== Thunderbird Email Organization Setup for Toby ==="
echo ""
echo "This script will guide you through setting up the email organization system."
echo "It will create folders and import message filters to automatically organize your email."
echo ""

# Check Thunderbird is running
if ! pgrep -f "thunderbird" > /dev/null; then
    echo "ERROR: Thunderbird is not running. Please start Thunderbird first."
    exit 1
fi

echo "Thunderbird is running. Proceeding with setup..."
echo ""

# Create backup of current settings
BACKUP_DIR="$HOME/thunderbird_backup_$(date +%Y%m%d_%H%M%S)"
echo "Creating backup of current Thunderbird settings to: $BACKUP_DIR"
mkdir -p "$BACKUP_DIR"
cp -r "$HOME/snap/thunderbird/common/.thunderbird" "$BACKUP_DIR/"
echo "Backup created."
echo ""

echo "=== STEP 1: Folder Creation ==="
echo ""
echo "You will need to create the following folders in Thunderbird:"
echo ""
echo "For each email account (toby@alphaconstructionpros.com and tobymilleragency@gmail.com):"
echo "  - Action"
echo "  - Clients" 
echo "  - Finance-Receipts"
echo "  - Vendors"
echo "  - Personal"
echo "  - Newsletters"
echo "  - Promotions"
echo "  - Spam-Review"
echo "  - Archive"
echo ""
echo "To create folders in Thunderbird:"
echo "1. Right-click on your email account in the left sidebar"
echo "2. Select 'New Folder...'"
echo "3. Enter the folder name and click 'Create Folder'"
echo "4. Repeat for each folder listed above"
echo ""
echo "Press Enter when you have created all the folders..."
read -p ""

echo ""
echo "=== STEP 2: Message Filter Import ==="
echo ""
echo "Now we'll import the message filter rules:"
echo ""
echo "1. In Thunderbird, go to Tools > Message Filters"
echo "2. Click 'Import' button"
echo "3. Navigate to: $(pwd)"
echo "4. Select the file 'thunderbird_filters.txt'"
echo "5. Click 'Open' to import the filters"
echo ""
echo "The filters will automatically:"
echo "- Protect important senders (Jeriko/AI related)"
echo "- Move spam to Spam-Review folder"
echo "- Organize financial documents"
echo "- Sort vendor communications"
echo "- Separate newsletters and promotions"
echo "- Archive emails older than 3 days"
echo ""
echo "Press Enter when you have imported the filters..."
read -p ""

echo ""
echo "=== STEP 3: Filter Configuration ==="
echo ""
echo "After importing, please verify the following:"
echo ""
echo "1. All filters are enabled (checkboxes checked)"
echo "2. Filter order is correct (important filters first)"
echo "3. Each filter has the correct target folder selected"
echo ""
echo "To adjust filter order: Use the 'Move Up'/'Move Down' buttons"
echo "To enable/disable: Check/uncheck the boxes next to each filter"
echo ""
echo "Press Enter when filters are configured..."
read -p ""

echo ""
echo "=== STEP 4: Testing the System ==="
echo ""
echo "Let's test the organization system:"
echo ""
echo "1. Send yourself a test email with 'newsletter' in the subject"
echo "2. Send yourself a test email with 'invoice' in the subject"
echo "3. Wait a few minutes for filters to process"
echo "4. Check that emails are moved to correct folders"
echo ""
echo "Press Enter when ready to test..."
read -p ""

echo ""
echo "=== STEP 5: Manual Organization Guidelines ==="
echo ""
echo "For existing emails in your inbox:"
echo ""
echo "1. Review emails older than 3 days"
echo "2. Manually move non-urgent emails to Archive folder"
echo "3. Keep only actionable emails in Inbox"
echo "4. Use 'Action' folder for emails requiring response"
echo "5. Use 'Clients' folder for client-related emails"
echo ""
echo "DO NOT mass-delete emails - move them to appropriate folders instead"
echo ""

echo ""
echo "=== SETUP COMPLETE ==="
echo ""
echo "Your Thunderbird email organization system is now configured!"
echo ""
echo "Daily workflow:"
echo "- Keep Inbox for emails requiring action in next 3 days"
echo "- Use Action folder for longer-term tasks"
echo "- Check Newsletters/Promotions when convenient"
echo "- Review Spam-Review folder weekly for false positives"
echo ""
echo "Weekly maintenance:"
echo "- Review Spam-Review folder"
echo "- Archive emails older than 3 days from Inbox"
echo "- Process Action folder"
echo ""
echo "Monthly maintenance:"
echo "- Clean up Archive folder if needed"
echo "- Review filter effectiveness"
echo "- Update protected senders list if needed"
echo ""
echo "Backup location: $BACKUP_DIR"
echo "Filter rules location: $(pwd)/thunderbird_filters.txt"
echo "Organization plan: $(pwd)/email_organization_plan.txt"
echo ""
echo "System is ready to use!"